
security:
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        Julie\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_VISITOR: ROLE_USER
        ROLE_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_SUPER_ADMIN]
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username

    access_control:
        - { path: ^/nouvelleGalerie,    roles: ROLE_SUPER_ADMIN }
        - { path: ^/edit,               roles: ROLE_SUPER_ADMIN }
        - { path: ^/delete,             roles: ROLE_SUPER_ADMIN }
        - { path: ^/studio,             roles: ROLE_SUPER_ADMIN }
        - { path: ^/_console,           roles: ROLE_SUPER_ADMIN }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                
            logout:
                path:       fos_user_security_logout
                target:     /home
            remember_me:
                key:        %secret%
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
