services:
#    julie_platform.example:
#        class: Julie\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    julie_platform.menu_builder:
        class:						Julie\PlatformBundle\Menu\MenuBuilder
        arguments:				['@knp_menu.factory', '@doctrine.orm.entity_manager']

    julie_platform.menu.main:
        class:						Knp\Menu\MenuItem
        factory_service:	julie_platform.menu_builder
        factory_method:		createMainMenu
        tags:
            - { name: knp_menu.menu, alias: main }