parameters:
        julie_user_bundle.component.authentication.handler.login_success_handler.class: Julie\UserBundle\Component\Authentication\Handler\LoginSuccessHandler

services:
#    julie_platform.example:
#        class: Julie\PlatformBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    julie_platform_bundle.menu_builder:
        class:						Julie\PlatformBundle\Menu\MenuBuilder
        arguments:					['@knp_menu.factory', '@doctrine.orm.entity_manager']

    julie_platform_bundle.menu.main:
        class:						Knp\Menu\MenuItem
        factory_service:			julie_platform.menu_builder
        factory_method:				createMainMenu
        tags:
            - { name: knp_menu.menu, alias: main }